//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaDisc.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaDisc.Data.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        public static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is licensed under the GPL-3.0 License.
        /// </summary>
        public static string appLicenseInfo {
            get {
                return ResourceManager.GetString("appLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LunaDisc.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.08.0-alpha1.
        /// </summary>
        public static string appVersion {
            get {
                return ResourceManager.GetString("appVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Version Info:.
        /// </summary>
        public static string appVersionAdvanced {
            get {
                return ResourceManager.GetString("appVersionAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string appVersionPrefix {
            get {
                return ResourceManager.GetString("appVersionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Browser....
        /// </summary>
        public static string clearBrowser {
            get {
                return ResourceManager.GetString("clearBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Directory.
        /// </summary>
        public static string dlgCreateDirectoryHeader {
            get {
                return ResourceManager.GetString("dlgCreateDirectoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename .
        /// </summary>
        public static string dlgRenameHeader {
            get {
                return ResourceManager.GetString("dlgRenameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string fileCtxMenu {
            get {
                return ResourceManager.GetString("fileCtxMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Directories....
        /// </summary>
        public static string getDirectories {
            get {
                return ResourceManager.GetString("getDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Files....
        /// </summary>
        public static string getFiles {
            get {
                return ResourceManager.GetString("getFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an Disc Image.
        /// </summary>
        public static string openImage {
            get {
                return ResourceManager.GetString("openImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string preferencesTitle {
            get {
                return ResourceManager.GetString("preferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique name below..
        /// </summary>
        public static string renameDescription {
            get {
                return ResourceManager.GetString("renameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Browser....
        /// </summary>
        public static string updateList {
            get {
                return ResourceManager.GetString("updateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Up a Directory.
        /// </summary>
        public static string upDirectory {
            get {
                return ResourceManager.GetString("upDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the GitHub Repository.
        /// </summary>
        public static string visitGit {
            get {
                return ResourceManager.GetString("visitGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume ID: .
        /// </summary>
        public static string volumeId {
            get {
                return ResourceManager.GetString("volumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Information.
        /// </summary>
        public static string volumeInfo {
            get {
                return ResourceManager.GetString("volumeInfo", resourceCulture);
            }
        }
    }
}
